name: Test New Control Flow Functions
description: Test ifElse, partitionByCondition, and tryCatch
trigger: manual
output: json
steps:
  - module: utilities.javascript.evaluateExpression
    id: setup
    inputs:
      expression: "({users: [{id: 1, name: 'Alice', score: 95}, {id: 2, name: 'Bob', score: 75}, {id: 3, name: 'Charlie', score: 88}], threshold: 80})"
    outputAs: data

  # Test partitionByCondition - splits array
  - module: utilities.control-flow.partitionByCondition
    id: partition-users
    inputs:
      items: "{{data.users}}"
      field: score
      operator: ">"
      value: "{{data.threshold}}"
    outputAs: partitioned

  # Calculate if has high performers
  - module: utilities.javascript.execute
    id: calc-has-high-perf
    inputs:
      code: "return matched.length > 0"
      context:
        matched: "{{partitioned.matched}}"
    outputAs: hasHighPerformers

  # Test ifElse - simple branching
  - module: utilities.control-flow.ifElse
    id: check-high-performers
    inputs:
      condition: "{{hasHighPerformers}}"
      ifTrue: "Has high performers"
      ifFalse: "No high performers"
    outputAs: performanceStatus

  # Test tryCatch - error handling
  - module: utilities.control-flow.tryCatch
    id: safe-operation
    inputs:
      attemptValue:
        status: success
        data: "{{partitioned.matched}}"
      errorValue:
        status: error
        data: []
    outputAs: safeResult

  - module: utilities.javascript.execute
    id: final-report
    inputs:
      code: |
        return {
          highPerformers: partitioned.matched.length,
          lowPerformers: partitioned.unmatched.length,
          status: status,
          result: result
        }
      context:
        partitioned: "{{partitioned}}"
        status: "{{performanceStatus}}"
        result: "{{safeResult}}"
    outputAs: report
