name: Universal AI Assistant
description: General purpose AI agent with full tool access for testing
trigger: chat
output: markdown
category: ai-agents
tags: [chat, ai, tools, test]
steps:
  - module: ai.ai-agent.runAgent
    id: agent
    inputs:
      prompt: "{{trigger.userMessage}}"
      model: gpt-4o-mini
      maxSteps: 15
      temperature: 0.7
      systemPrompt: |
        You are a helpful AI assistant with access to various tools.
        Use tools when needed to provide accurate, up-to-date information.
        Be concise but thorough in your responses.
      toolOptions:
        useAll: true
    outputAs: agentResponse
