name: Test Validation Error Detection
description: Workflow to test enhanced validation features
trigger: cron
output: json
returnValue: "{{aiResult}}"
steps:
  - module: utilities.math.add
    id: step1
    inputs:
      a: 10
      b: 20
    outputAs: result1

  - module: utilities.array-utils.sum
    id: step2
    inputs:
      arr: [1, 2, 3]
    outputAs: result2

  - module: utilities.array-utils.max
    id: step3
    inputs:
      arr: [1, 2, 3]
    outputAs: result3

  - module: ai.ai-sdk.generateText
    id: ai-step
    inputs:
      prompt: "Test"
      model: gpt-4o-mini
      provider: openai
      apiKey: "{{credential.openai_api_key}}"
    outputAs: aiResult
