#!/bin/bash

# Script to export environment variables for Railway
# This reads your .env file and formats it for Railway CLI

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Railway Environment Variable Export ===${NC}\n"

# Check if .env file exists
if [ ! -f .env ]; then
    echo "Error: .env file not found in current directory"
    exit 1
fi

# Check if railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo -e "${YELLOW}Warning: Railway CLI not installed${NC}"
    echo "Install it with: npm install -g @railway/cli"
    echo ""
fi

echo "Reading variables from .env file..."
echo ""

# Parse .env file and generate railway commands
while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines and comments
    if [[ -z "$line" ]] || [[ "$line" =~ ^#.*$ ]]; then
        continue
    fi

    # Extract key=value
    if [[ "$line" =~ ^([^=]+)=(.*)$ ]]; then
        key="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]}"

        # Remove inline comments from value
        value=$(echo "$value" | sed 's/#.*//' | sed 's/[[:space:]]*$//')

        # Remove quotes if present
        value=$(echo "$value" | sed 's/^"//' | sed 's/"$//')

        # Skip if value is empty or a placeholder
        if [[ -z "$value" ]] || [[ "$value" == *"your_"* ]] || [[ "$value" == *"_here"* ]]; then
            echo -e "${YELLOW}Skipping $key (empty or placeholder)${NC}"
            continue
        fi

        # Skip Railway auto-generated and localhost-specific variables
        if [[ "$key" == "DATABASE_URL" ]] || [[ "$key" == "REDIS_URL" ]] || \
           [[ "$key" == "REDIS_HOST" ]] || [[ "$key" == "REDIS_PORT" ]] || \
           [[ "$key" == "REDIS_PASSWORD" ]]; then
            echo -e "${YELLOW}Skipping $key (auto-generated by Railway or localhost-specific)${NC}"
            continue
        fi

        # Update production-specific values
        if [[ "$key" == "AUTH_URL" ]] && [[ "$value" == "http://localhost:3000" ]]; then
            echo -e "${YELLOW}⚠️  AUTH_URL is localhost - update to your Railway URL${NC}"
            echo -e "${YELLOW}   railway variables set AUTH_URL=\"https://your-app.up.railway.app\"${NC}"
            continue
        fi

        if [[ "$key" == "NODE_ENV" ]] && [[ "$value" == "development" ]]; then
            value="production"
            echo -e "${YELLOW}Changed NODE_ENV from development to production${NC}"
        fi

        # Generate railway command
        echo "railway variables set $key=\"$value\""
    fi
done < .env

echo ""
echo -e "${GREEN}=== Instructions ===${NC}"
echo "1. Review the commands above"
echo "2. Copy the 'railway variables set' commands you want to use"
echo "3. Run them in your terminal (make sure you're in the right Railway project)"
echo ""
echo "Or run this script with bash and pipe to bash:"
echo "  bash scripts/export-railway-env.sh | grep 'railway variables set' | bash"
